default:
  image: node:18-alpine

build:
  stage: build
  script:
    - npm ci
    - npm run lint
    - npm run build

test:unit:
  stage: test
  script:
    - npm ci
    - npm run test

test:e2e:
  stage: test
  script:
    - npm ci
    - npm run test:e2e
