default:
  image: node:18-alpine

.cache:
  cache:
    key:
      files:
        - package.json
    paths:
      - node_modules
    policy: pull

build:
  stage: build
  extends:
    - .cache
  script:
    - npm ci
    - npm run lint
    - npm run build
  cache:
    policy: pull-push # Overwrite policy

test:unit:
  stage: test
  extends:
    - .cache
  script:
    - npm run test

test:e2e:
  stage: test
  extends:
    - .cache
  script:
    - npm run test:e2e

deploy:
  stage: deploy
  script:
    - echo "POSTGRES_USER=$POSTGRES_USER" >> .env
    - echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> .env
    - echo "PGADMIN_DEFAULT_EMAIL=$PGADMIN_DEFAULT_EMAIL" >> .env
    - echo "PGADMIN_DEFAULT_PASSWORD=$PGADMIN_DEFAULT_PASSWORD" >> .env
    - docker compose down --remove-orphans
    - docker compose up -d --force-recreate
  only:
    - main@noalino/wankul-tcg-backend
  tags:
    - linux
    - shell
