version: '3'

services:
  api:
    build:
      context: .
      target: run
    container_name: api
    ports:
      - 3010:3000
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: wankuldb
    depends_on:
      - db
    networks:
      - postgres

  doc:
    build:
      context: .
      target: serve-doc
    container_name: doc
    ports:
      - 3011:8080

  db:
    image: postgres:15.4
    container_name: postgres
    ports:
      - 3012:5432
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./config/db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: wankuldb
    env_file:
      - .env
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:7.5
    container_name: pgadmin
    ports:
      - 3013:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    env_file:
      - .env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  db_data:
  pgadmin_data:
