version: '3'

services:
  api:
    build:
      context: .
      target: install-dependencies
    container_name: api
    command: npm run start:dev
    volumes:
      - ./src:/user/src/app/src
    env_file:
      - .env
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - db
    networks:
      - postgres

  db:
    image: postgres:15.4
    container_name: postgres
    ports:
      - ${PG_HOST_PORT}:${POSTGRES_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./config/db:/docker-entrypoint-initdb.d
    env_file:
      - docker.env
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:7.5
    container_name: pgadmin
    ports:
      - ${PGADMIN_HOST_PORT}:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    env_file:
      - docker.env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  db_data:
  pgadmin_data:
