version: '3'

services:
  api:
    build:
      context: .
      target: install-dependencies
    container_name: api
    command: pnpm start:dev
    volumes:
      - ./src:/user/src/app/src
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - db
    networks:
      - postgres

  db:
    image: postgres:15.4
    container_name: postgres
    ports:
      - '54320:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - docker.env
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:7.5
    container_name: pgadmin
    ports:
      - '5050:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    env_file:
      - docker.env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  db_data:
  pgadmin_data:
